[SOURCE]
job_postings = s3a://raw-zone-layer/postings/postings.csv
job_skills = s3a://raw-zone-layer/job_skills/job_skills.csv
job_industries = s3a://raw-zone-layer/job_industries/job_industries.csv
industries = s3a://raw-zone-layer/industries/industries.csv
skills = s3a://raw-zone-layer/skills/skills.csv
zip_state_mapping = s3a://raw-zone-layer/zip_state_mapping/zip_state_mapping.csv

[DESTINATION]
s3_path = s3a://processed-zone-layer/linkedin_postings/

[TRANSFORM]
sql_path = sql/linkedin_postings.sql

[VALIDATION]
unique_keys = job_id,company_id

[RDS]
host = database-1.ccnsaqom8qmn.us-east-1.rds.amazonaws.com
port = 3306
username = admin
password = Suryamysql5
database = project_linkedin
schema = consumption
table = linden_postings
